### ISSUE TITLE
Newlines in pin body cause JSON to fail to parse

### ISSUE THREAD

**Issue by Willow-Systems** [Willow-Systems/ws-pebble-timeline-services#8]
If any of the fields contain newlines, the JSON object doesn't parse and the pin isn't created.

Find+Replace newlines before trying JSON.parse()

**Comment by kennedn** [comment]
I was the original reporter for this issue in the discord. However looking further, this may be be a non-issue. It appears you can escape variable content in IFTTT with <<< >>> syntax in a given applets body. Testing locally and will report back.

**Comment by kennedn** [comment]
Seems to be remedied. I was able to receive a multi-line pin today after escaping the variable content in IFTTT.
